server:
  port: 8080
  connectionTimeout: 180000
  servlet:
    context-path: /
    session:
      timeout: 86400
spring:
  application:
    name: food
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB