spring:
  data:
    elasticsearch:
      cluster-name: myes #必须和/etc/elasticsearch.yml中的集群名字相同
      cluster-nodes: 192.168.33.100:9300
      repositories:
        enabled: true

  kafka:
    #kafka可以配置多个
    bootstrap-servers: 192.168.33.100:9092
    consumer:
      group-id: test
      enable-auto-commit: true
      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

